### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
!pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[435, 268, 143, 404], [435, 268, 143, 293], [435, 96, 143, 471], [467, 7, 402, 25, 454], [467, 7, 402, 25, 140], [399, 435, 56, 143, 102], [172, 136, 24, 25]]


### Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 435 268 143 404]
 [  0   0   0   0 435 268 143 293]
 [  0   0   0   0 435  96 143 471]
 [  0   0   0 467   7 402  25 454]
 [  0   0   0 467   7 402  25 140]
 [  0   0   0 399 435  56 143 102]
 [  0   0   0   0 172 136  24  25]]


In [ ]:
## 10 feature dimesnions
dim=10


In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 435, 268, 143, 404], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 161ms/step


array([[ 0.01488515, -0.00981277,  0.00469238, -0.04055492, -0.02749711,
        -0.03418574, -0.02973739,  0.04330026,  0.04221939,  0.0288546 ],
       [ 0.01488515, -0.00981277,  0.00469238, -0.04055492, -0.02749711,
        -0.03418574, -0.02973739,  0.04330026,  0.04221939,  0.0288546 ],
       [ 0.01488515, -0.00981277,  0.00469238, -0.04055492, -0.02749711,
        -0.03418574, -0.02973739,  0.04330026,  0.04221939,  0.0288546 ],
       [ 0.01488515, -0.00981277,  0.00469238, -0.04055492, -0.02749711,
        -0.03418574, -0.02973739,  0.04330026,  0.04221939,  0.0288546 ],
       [-0.01364316, -0.02296036,  0.04643604, -0.02814175,  0.00422627,
         0.02039664, -0.00160687,  0.04866246, -0.04543972, -0.0340877 ],
       [ 0.04491904,  0.02892694,  0.0107829 , -0.00968527, -0.01944584,
        -0.0332089 , -0.00692285,  0.00106732,  0.02176644, -0.02065235],
       [-0.03690177, -0.03604557, -0.02662674, -0.043931  ,  0.00063968,
        -0.03365912, -0.01822188,  0.03996331

In [ ]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 58ms/step
[[[ 0.01488515 -0.00981277  0.00469238 -0.04055492 -0.02749711
   -0.03418574 -0.02973739  0.04330026  0.04221939  0.0288546 ]
  [ 0.01488515 -0.00981277  0.00469238 -0.04055492 -0.02749711
   -0.03418574 -0.02973739  0.04330026  0.04221939  0.0288546 ]
  [ 0.01488515 -0.00981277  0.00469238 -0.04055492 -0.02749711
   -0.03418574 -0.02973739  0.04330026  0.04221939  0.0288546 ]
  [ 0.01488515 -0.00981277  0.00469238 -0.04055492 -0.02749711
   -0.03418574 -0.02973739  0.04330026  0.04221939  0.0288546 ]
  [-0.01364316 -0.02296036  0.04643604 -0.02814175  0.00422627
    0.02039664 -0.00160687  0.04866246 -0.04543972 -0.0340877 ]
  [ 0.04491904  0.02892694  0.0107829  -0.00968527 -0.01944584
   -0.0332089  -0.00692285  0.00106732  0.02176644 -0.02065235]
  [-0.03690177 -0.03604557 -0.02662674 -0.043931    0.00063968
   -0.03365912 -0.01822188  0.03996331  0.04276402  0.03242205]
  [-0.02240217 -0.0327435   0.03530127 -0.02347015 -0.01018

In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0, 435, 268, 143, 404], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 26ms/step
[[ 0.01488515 -0.00981277  0.00469238 -0.04055492 -0.02749711 -0.03418574
  -0.02973739  0.04330026  0.04221939  0.0288546 ]
 [ 0.01488515 -0.00981277  0.00469238 -0.04055492 -0.02749711 -0.03418574
  -0.02973739  0.04330026  0.04221939  0.0288546 ]
 [ 0.01488515 -0.00981277  0.00469238 -0.04055492 -0.02749711 -0.03418574
  -0.02973739  0.04330026  0.04221939  0.0288546 ]
 [ 0.01488515 -0.00981277  0.00469238 -0.04055492 -0.02749711 -0.03418574
  -0.02973739  0.04330026  0.04221939  0.0288546 ]
 [-0.01364316 -0.02296036  0.04643604 -0.02814175  0.00422627  0.02039664
  -0.00160687  0.04866246 -0.04543972 -0.0340877 ]
 [ 0.04491904  0.02892694  0.0107829  -0.00968527 -0.01944584 -0.0332089
  -0.00692285  0.00106732  0.02176644 -0.02065235]
 [-0.03690177 -0.03604557 -0.02662674 -0.043931    0.00063968 -0.03365912
  -0.01822188  0.03996331  0.04276402  0.03242205]
 [-0.02240217 -0.0327435   0.03530127 -0.02347015 -0.01018832 -0.0041074
 

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[435, 279, 424, 402, 34, 49], [316, 459, 424, 286, 280, 328], [467, 42, 255, 79], [435, 65, 424, 187, 435, 314], [19, 262, 481, 424, 286, 280, 328], [196, 424, 286, 280, 357, 145]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0 435 279 424 402  34  49]
 [  0   0 316 459 424 286 280 328]
 [  0   0   0   0 467  42 255  79]
 [  0   0 435  65 424 187 435 314]
 [  0  19 262 481 424 286 280 328]
 [  0   0 196 424 286 280 357 145]]
